/*
 * (C) Copyright 20014 - 2017 Leo C. <erbl259-lmu@yahoo.de>
 *
 * SPDX-License-Identifier: GPL-2.0
 */

#include "timer.h"
#include <libopencm3/cm3/nvic.h>
#include <libopencm3/cm3/systick.h>
#include <libopencm3/stm32/rcc.h>


/*
 * timer interrupt/overflow counter, counts up every ms.
 */
static
volatile uint32_t timestamp;

void systick_setup(void)
{
    /* SysTick interrupt every N clock pulses: set reload to N-1 */
    STK_RVR = rcc_ahb_frequency/1000 - 1;

    /* Set source to core clock, enable int and start counting. */
    STK_CSR = STK_CSR_CLKSOURCE_AHB | STK_CSR_TICKINT | STK_CSR_ENABLE;
}

/*--------------------------------------------------------------------------*/

/*
 * 1000Hz timer interrupt generated by System Timer
 */
void sys_tick_handler(void)
{
    ++timestamp;
}

/*--------------------------------------------------------------------------*/

/*
 * Return elapsed time in ms since base.
 */
uint32_t get_timer(uint32_t base)
{
    return timestamp - base;
}
